name: backend-eslint

on:
  push:
    branches:
      - "master"
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - "master"
    paths:
      - 'backend/**'

env:
  BACKEND_PATH: backend


jobs:
  lint:
    name: Run eslint (backend)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ${{ env.BACKEND_PATH }}/.node-version
          cache: npm
          cache-dependency-path: ${{ env.BACKEND_PATH }}/package-lock.json

      - name: Install dependencies (backend)
        working-directory: ${{ env.BACKEND_PATH }}
        run: npm ci

      - name: Run ESLint
        working-directory: ${{ env.BACKEND_PATH }}
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npm run lint:sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.BACKEND_PATH }}/eslint-results.sarif
          wait-for-processing: true